export const TAG_STORAGE_NAME = "AWESOME_GAME_LIST_DATA_TAGS";
export const ITEM_STORAGE_NAME = "AWESOME_GAME_LIST_DATA_GAMES";
export const PLATFORM_STORAGE_NAME = "AWESOME_GAME_LIST_DATA_PLATFORMS";
